# Site settings
title: chasum
url: "https://chasum.net"
# Homepage settings
name: Thibault Charbonnier
description: >
    All things Linux/NGINX/LuaJIT. iOS/Node.js/Frontend in a previous life.
job_title: >
    Principal Engineer @ [Kong Inc.](https://konghq.com)

# Build settings
source: ./site
disable_disk_cache: true
permalink: pretty
sass:
  sass_dir: assets/css
  style: compressed

